osx_image: xcode9.3
language: objective-c

branches:
  only:
    - master

env:
  - DESTINATION='platform=iOS Simulator,name=iPhone 6S' POD_LINT="YES"

before_install:
 - gem install xcpretty-travis-formatter

script:
  - set -o pipefail
  - xcodebuild -scheme SunshineKit -destination "$DESTINATION" test | xcpretty -f `xcpretty-travis-formatter`

  - if [ "$POD_LINT" = "YES" ]; then
     pod lib lint;
    fi

  # Run release to master branch
  - if [ "$POD_LINT" = "YES" ] && [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      pod spec lint;
    fi
