osx_image: xcode9.3
language: objective-c

branches:
  only:
    - master

env:
  - DESTINATION='platform=OS X' POD_LINT="YES"
  - DESTINATION='platform=iOS Simulator,name=iPhone 6S'
  - DESTINATION='platform=watchOS Simulator,name=Apple Watch - 38mm' SKIP_TEST="YES"
  - DESTINATION='platform=tvOS Simulator,name=Apple TV 4K'

before_install:
 - gem install xcpretty-travis-formatter

script:
  - set -o pipefail
  - xcodebuild -scheme SunKit -destination "$DESTINATION" test | xcpretty -f `xcpretty-travis-formatter`

  - if [ "$POD_LINT" = "YES" ]; then
     pod lib lint;
    fi

  # Run release to master branch
  - if [ "$POD_LINT" = "YES" ] && [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      pod spec lint;
    fi
